### ISSUE TITLE
Divers problème avec Dolibarr 8.0.2

### ISSUE THREAD

**Issue by vincentxavier** [Darkjeff/immobilier#22]
L'installation du plugin se passe bien sous Dolibarr 8.0.2 mais divers comportement étranges (menu ne fonctionnant pas, locataires non saisis en base, …) empêche l'utilisation du greffon.

**Comment by mikygee** [comment]
Bonjour,
Est-ce que le problème est toujours d'actualité ?
Cdt

**Comment by mikygee** [comment]
Bonjour Vincent,
Le mieux serait de clôturer ce ticket.
Datant d'il y a 4 ans, il n'est plus pertinent.
Merci
