### ISSUE TITLE
Is still maintained?

### ISSUE THREAD

**Issue by rimiti** [Darkjeff/immobilier#25]
Hello @Darkjeff ,

I'd like to know if the project is still maintained.

Regards,

**Comment by Darkjeff** [comment]
Hi we have a new project on framagit 

I began a group in order to finance the new version ^^

**Comment by rimiti** [comment]
Ok nice!
What's the name of the new projet? Can you share the link?
If you need some help to develop the new project, it's possible. Just let me know.
