### ISSUE TITLE
rattachement Bien Parent

### ISSUE THREAD

**Issue by bv74** [Darkjeff/immobilier#34]
Bonjour,
Dans le menu "Biens" le rattachement à un bien parent n'est pas possible. La liste des biens disponibles n'apparait pas dans le champs « Bien Parent ».

**Comment by Darkjeff** [comment]
oui est en en train de tout reprendre depuis le début

**Comment by bv74** [comment]
Pour info release : 0e9dffa

**Comment by bv74** [comment]
Bonjour, 
le soucis existe encore avec la version du 14/12/2021. 
Cdlt. 
B

**Comment by bv74** [comment]
Le problème est réglé si on renseigne le champ libellé. Ce champ ne devrait-il pas être obligatoire ?
