### ISSUE TITLE
Modèle de quittance absent

### ISSUE THREAD

**Issue by mikewiza** [Darkjeff/immobilier#38]
En voulant générer une quittance on obtient l'erreur suivante :

_**Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20211104173455
Dolibarr: 13.0.5 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.4.3
Server: Apache/2.4.41 (Ubuntu)
OS: Linux sv-dolibarr 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64
UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0

Url sollicitée: /dolibarr/htdocs/custom/ultimateimmo/receipt/immoreceipt_card.php?action=builddoc&id=12
Referer: http://192.168.30.13/dolibarr/htdocs/custom/ultimateimmo/receipt/immoreceipt_card.php?id=12&save_lastsearch_values=1
Gestionnaire de menu: auguria_menu.php

Modules/Applications: user, societe, banque, ultimateimmo
Message: Erreur Failed to load doc generator with modelpaths=ultimateimmo/core/modules/ultimateimmo/doc/ - modele=quittance**_

Si on va dans la config du module UltimateImmo on s'aperçoit qu'il n'y a pas de modèle.
![modèle_quittance](https://user-images.githubusercontent.com/93732926/140402648-fc134411-7561-4928-9998-b399dc6638f2.png)

**Comment by mikewiza** [comment]
Depuis la dernière mise à jours, il est possible de générer les quittances mais

**Comment by Darkjeff** [comment]
il faut utiliser nouveau paiement qui permet du multiple paiement (enfin moi c'est ce que j'utilise sur ma version de prod

**Comment by mikewiza** [comment]
![Paiement](https://user-images.githubusercontent.com/93732926/148558763-359e967a-f03e-4976-a543-068948bf78fc.png)
On parle bien de ce masque?
Lorsque l'on fait CREATE on  obtient:


Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20220107120241
Dolibarr: 13.0.5 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.4.3
Server: Apache/2.4.41 (Ubuntu)
OS: Linux sv-dolibarr 5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; rv:95.0) Gecko/20100101 Firefox/95.0

Url sollicitée: /dolibarr/htdocs/custom/ultimateimmo/payment/immopayment_card.php
Referer: http://192.168.30.13/dolibarr/htdocs/custom/ultimateimmo/payment/immopayment_card.php?action=create&backtopage=%2Fdolibarr%2Fhtdocs%2Fcustom%2Fultimateimmo%2Fpayment%2Fimmopayment_list.php
Gestionnaire de menu: auguria_menu.php

Modules/Applications: user, societe, banque, ultimateimmo
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: Aucune requête en erreur
Code retour dernier accès en base en erreur: Aucune requête en erreur
Information sur le dernier accès en base en erreur: Aucune requête en erreur

Message: **Payement not found in database**

**Comment by Darkjeff** [comment]
faut utiliser celui la 
/custom/ultimateimmo/payment/immopayment_card.php?action=createall

**Comment by mikewiza** [comment]
Vous pouvez attacher une copie d'écran. Je ne comprend pas!

**Comment by Darkjeff** [comment]
![image](https://user-images.githubusercontent.com/1095260/148565086-ca33e74b-848d-48ef-b9e0-880a9283a9fc.png)

**Comment by mikewiza** [comment]
J'ai créé 2 quittances qui sont impayées mais le masque paiement reste désespérément vide 
![Paiement2](https://user-images.githubusercontent.com/93732926/148570883-3919d529-adee-4ba7-8b1f-e1678420bb09.png)

**Comment by mikewiza** [comment]
Bonjour
Depuis le commit d2a166d et la migration de Dolibarr de la version 13 vers la 14.0.5. Il est maintenant possible de saisir le réglement de la quittance. 
Il est néanmoins nécessaire d'éditer la BD avec phpMyAdmin pour modifier certaines valeurs par défaut
![Field_ref_default_value_immopayment](https://user-images.githubusercontent.com/93732926/152756547-2f8796e7-ec80-4e05-b1fa-38230b03c67f.png)
J'ai également modifié la table immorent pour utiliser des nombres à virgule:
![Table_immorent](https://user-images.githubusercontent.com/93732926/152758661-a4dfce93-12e0-4757-9bb4-bb688d175682.png)

Merci encore pour le travail
