### ISSUE TITLE
Depuis la dernière mise à jours, il est possible de générer les quittances mais lorsque l'on clique sur saisir règlement on obtient une page blanche "Include of main fails". C'est une erreur PHP mais encore?

### ISSUE THREAD

**Issue by mikewiza** [Darkjeff/immobilier#41]
Depuis la dernière mise à jours, il est possible de générer les quittances mais lorsque l'on clique sur saisir règlement on obtient une page blanche "Include of main fails". C'est une erreur PHP mais encore?
D'autre part j'ai configuré l'envoie de mails via GMAIL, le mail est bien envoyé mais sans la pièce jointe en l'occurrence la quittance ou tout autre fichier(joindre ce fichier)

_Originally posted by @mikewiza in https://github.com/Darkjeff/immobilier/issues/38#issuecomment-1006798023_

**Comment by mikewiza** [comment]
La génération des quittances fonctionne depuis le commit d2a166d avec Dolibarr 14.0.5

**Comment by FHenry** [comment]
C'est précisémment ce commit qui corrige la saisie des paiement 
[#d747b99470034a1345fa62bfd632d59fd4ed1572](https://github.com/Darkjeff/immobilier/commit/d747b99470034a1345fa62bfd632d59fd4ed1572)
