### ISSUE TITLE
Onglet Quittances Charges locatives restent vide

### ISSUE THREAD

**Issue by mikewiza** [Darkjeff/immobilier#45]
Pour les charges locatives:

Les tableaux des coûts locataire et résultats statistiques restent vide:
![Charges_Locatives_Coût_locataire](https://user-images.githubusercontent.com/93732926/153571778-b44ed16b-fd80-45ef-a6ba-54b91710d849.png)
![Charges_Locatives_Stats](https://user-images.githubusercontent.com/93732926/153572225-a76b5ed7-a039-4abd-9284-60e7e4557f22.png)
Y 'a t'il un paramétrage pour que cela fonctionne?

**Comment by bv74** [comment]
Bonjour, 

version 14.0.5 l'onglet quittance reste non renseigné.

**Comment by FHenry** [comment]
Il faut creer des batiment et des propriété (bien) qui sont dedans
