### ISSUE TITLE
data.sql

### ISSUE THREAD

**Issue by doudouvs** [Darkjeff/immobilier#47]
Par défaut il ne charge pas le sql/data.sql et

`INSERT INTO llx_c_ultimateimmo_juridique(rowid,code,label,active) VALUES (0, 'MONO_PROP', 'Mono propriété', 1),(1, 'CO_PROP', 'Copropriété', 1);
`

la table code à un varchar de 8 alors que  "MONO_PROP" fait 9

**Comment by FHenry** [comment]
il faut désactivé et réactivé le module
