### ISSUE TITLE
paiement erreur sql

### ISSUE THREAD

**Issue by doudouvs** [Darkjeff/immobilier#48]
![Capture d’écran du 2022-04-06 10-55-13](https://user-images.githubusercontent.com/34343360/161942896-f78b2e77-d45b-4a6d-98b0-141fc77070cf.png)

**Comment by Darkjeff** [comment]
si on fait nouveau paiement ça fonctionne (le paiement multiple)

par contre le paiement direct depuis une quittance ne fonctionne plus 

j'essaye de corriger mais quand l'un fonctionne l'autre ne fonctionne plus ^^

le paiement multiple est plus pratique

**Comment by FHenry** [comment]
close by [6f66634](https://github.com/Darkjeff/immobilier/commit/6f66634e7404d085a890e7c1bdc5de22a7607a06)
