### ISSUE TITLE
Ajout d'un type de bien immobilier

### ISSUE THREAD

**Issue by bv74** [Darkjeff/immobilier#50]
Bonjour, 
j'ai voulu ajouter un nouveau type de bien immobilier : Terre cultivable. Pas de soucis à la création, mais il n'apparait pas dans la liste lors de la création d'un nouveau bien. J'ai 6 item de base, mais pas le 7ème créé. Il est bien entendu actif. 
Je trouve le type dans la table : llx_c_ultimateimmo_immoproperty_type

Où pourrait se trouver mon erreur de manip ?
Merci bien. 
BVA

**Comment by Darkjeff** [comment]
erreur de code 

dans immoproerty.class.php

ligne 104

	'property_type_id' => array('type' => 'integer', 'label' => 'ImmoProperty_Type', 'enabled' => 1, 'visible' => -1, 'position' => 20, 'notnull' => 1, 'arrayofkeyval' => array('1' => 'APA', '2' => 'HOU', '3' => 'LOC', '4' => 'SHO', '5' => 'GAR', '6' => 'BUL')),

et donc si ajout 7 ème il faudrait rajouter '7' =>'TEC'

si on rajoute ainsi dans le dictionnaire
![image](https://user-images.githubusercontent.com/1095260/170043062-77857296-1b13-4d0c-9320-e979eabf5fbb.png)


mais il faudrait que la liste aille chercher dans le dictionnaire directement

**Comment by bv74** [comment]
Bonjour, 

j'ai modifié la ligne 104 comme suit : 
`'property_type_id' => array('type' => 'integer', 'label' => 'ImmoProperty_Type', 'enabled' => 1, 'visible' => -1, 'position' => 20, 'notnull' => 1, 'arrayofkeyval' => array('1' => 'APA', '2' => 'HOU', '3' => 'LOC', '4' => 'SHO', '5' => 'GAR', '6' => 'BUL', '7' => 'TEC')),`

Mais je ne trouve pas dans la liste le nouvel item "Type de bien immobilier" dans la fiche du bien. 
Bonne journée.

**Comment by FHenry** [comment]
Maintenant issue du dictionnaire

**Comment by bv74** [comment]
Pb réglé fonctionne bien
