### ISSUE TITLE
Certaines sommes dans la listes des quittances sont erronées

### ISSUE THREAD

**Issue by bv74** [Darkjeff/immobilier#51]
Bonjour, 

les totaux des colonnes «paiements partiels» et «solde» sont erronés  dans _ultimateimmo/htdocs/custom/ultimateimmo/receipt/immoreceipt_list.php?socid=1&search_fk_soc=1_

Bien cordialement. 
BVA
PS : il ne m'est possible de mettre une copie d'écran. Désolé

**Comment by Darkjeff** [comment]
il faut valider les paiements je pense 

![image](https://user-images.githubusercontent.com/1095260/171015533-1322b7a2-f807-45f2-9293-af242a28e316.png)

**Comment by bv74** [comment]
les paiements sont effectués et je les retrouves bien.

**Comment by bv74** [comment]
OK
