### ISSUE TITLE
Libre et gratuit ?

### ISSUE THREAD

**Issue by RoseBlueRed** [Darkjeff/immobilier#60]
Salut, le plugin est bien gratuit pour l'utiliser sur Dolibarr ? Merci bien

**Comment by RoseBlueRed** [comment]
Salut, le plugin est bien gratuit pour l'utiliser sur Dolibarr ? Merci bien

**Comment by Darkjeff** [comment]
oui c'est open source 

si vous voulez aider les dev , vous pouvez acheter le module ultimate immo sur le dolistore

**Comment by RoseBlueRed** [comment]
> oui c'est open source 
> 
> 
> 
> si vous voulez aider les dev , vous pouvez acheter le module ultimate immo sur le dolistore 
> 
> 
> 
> 

La dernière version stable est la 15 ?

**Comment by FHenry** [comment]
La branche 15.0 est une version de test comptabilité avec 15.0.

La version "stable" mais (toujours en developpement) est la branche master
